language: c

services:
  - docker

env:
  - NIMBRANCH=devel ARCH=64
  - NIMBRANCH=devel ARCH=32
  - NIMBRANCH=version-0-19 ARCH=64
  - NIMBRANCH=version-0-19 ARCH=32

os:
  - linux
  - osx
  - windows

matrix:
  exclude:
    - os: osx
      env: NIMBRANCH=devel ARCH=32
    - os: osx
      env: NIMBRANCH=version-0-19 ARCH=32

branches:
  only:
    # Prevent building the auto tagged "untagged-*" commits.
    # https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches
    - master

addons:
  apt:
    update: true
    packages:
      - libcurl4-openssl-dev
      - libsdl1.2-dev
      - libgc-dev
      - libsfml-dev
      - nodejs

before_cache:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      brew cleanup
    fi

cache:
  directories:
    - nim
    - mingw
    - $HOME/Library/Caches/Homebrew

script:
  - . ./nightlies.sh

before_deploy:
  - git config --local user.name "${GIT_TAG_USER_NAME}"
  - git config --local user.email "${GIT_TAG_USER_EMAIL}"
  - export TRAVIS_TAG="${BUILD_DATE}-${NIMBRANCH}-${NIMVERSHORT}"
  - git tag "${TRAVIS_TAG}" || echo "${TRAVIS_TAG} already exists"
  - echo "[phase n-1] The deploy will start now .."

deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file: "${ASSETFILE}"
  name: "${TRAVIS_TAG} nightly build"
  body: >-
    This nightly release was built on ${BUILD_DATE} using https://github.com/nim-lang/Nim/tree/${NIMVER}.
    The Windows and Linux archives contain pre-packaged source as well as platform specific binaries
    whereas the OSX archive contains pre-packaged source only. Any of these archives can be used to
    build Nim on Windows, Linux and OSX.

  skip_cleanup: true
  on:
    condition: "! -z ${DO_DEPLOY+x}"
    tags: false

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
